### ISSUE TITLE
Implement Adam optimizer

### ISSUE THREAD

**Issue by vreis** [facebookresearch/ClassyVision#288]
## 🚀 Feature
Support for the Adam algorithm (https://pytorch.org/docs/stable/_modules/torch/optim/adam.html) within `classy_vision.optim`

## Motivation

Adam is a pretty standard optimizer.

## Pitch

Subclass ClassyOptimizer, similar to how we did SGD and RMSProp. 

## Alternatives

N/A

## Additional context

https://arxiv.org/abs/1412.6980
https://openreview.net/forum?id=ryQu7f-RZ

**Comment by TH3CHARLie** [comment]
Hi! I've submitted a PR #301 for this, please take a look
