### ISSUE TITLE
how to train FixResNeXt-101 32x*d?

### ISSUE THREAD

**Issue by iot-hunter** [facebookresearch/ClassyVision#305]
## ❓ Questions and Help

Before creating an issue, please go over our [Tutorials](https://classyvision.ai/tutorials) and [API Reference](https://classyvision.ai/api). If you cannot find the information you are looking for, please enquire in Classy Vision's `#help` [slack](https://classyvision.slack.com) channel before creating an issue.
I want to train FixResNeXt-101 32x48d or EfficientNet-B*  what should I do? thanks a lot

**Comment by mannatsingh** [comment]
Hi @iot-hunter , although the models you've mentioned aren't shipped with Classy Vision, the framework is built to support training any custom PyTorch models with ease. Please see the tutorial on [how to create a custom model](https://classyvision.ai/tutorials/classy_model) for more details.

**Comment by mannatsingh** [comment]
Closing this out
