### ISSUE TITLE
Separate train / eval code in tasks

### ISSUE THREAD

**Issue by aadcock** [facebookresearch/ClassyVision#308]
## 🚀 Feature
Currently the task abstraction just has a train step, but has two types of phases, train and test. So we end up having to take care of both training and evaluation in the same set of code (currently done with if-statements). The proposal is to improve the separation of the train / eval code by adding an eval_step to the tasks.

## Motivation

Currently we have two types of phases used during training, test phase and train phases. In test phases we use if-statements to turn off things like auto-grad and the backprop step. This is cumbersome and makes it harder to write separate logic for evaluation which many tasks need. 

## Pitch

What would need to be done:
1. Add an eval_step call to the task abstraction
2. Migrate current tasks (e.g. ClassificationTask) code to use train step and eval step
3. Update trainers to use eval step for test phases. Note, steps 2/3 are tricky because any user-created tasks will fail after 3 is done.

## Alternatives

Some alternatives we've thought about:

1. A drawback of the proposed solution is that if we want to do a new kind of evaluation, then we need to write a new task. So one solution is to have separate evaluation tasks. Then we can potentially mix and match training / eval setups. This pushes the requirement to the trainer to have a separate train and eval task. This could be a better solution and might be easier to migrate existing tasks without breaking them. cc @vreis 
2. Other solutions?

**Comment by vreis** [comment]
Done in https://github.com/facebookresearch/ClassyVision/pull/390
