### ISSUE TITLE
Implement more loss functions

### ISSUE THREAD

**Issue by Kongsea** [facebookresearch/ClassyVision#313]
Please implement more loss functions, such as focal loss, center loss...

**Comment by aadcock** [comment]
Hi @Kongsea , could you open separate issues for each loss function you are interested in being added (including links to the relevant literature and why you think it is important to add)? Then we can discuss each one separately and based on its own merits. (cc @vreis in case you have another idea in mind).

Also, it's quite easy to add custom loss functions to your local project for experimentation.

**Comment by Kongsea** [comment]
When I implement center loss, all features and output and target need to be passed to forward function. Then the following error was raised:
`RuntimeError: multi-target not supported at /pytorch/aten/src/THCUNN/generic/ClassNLLCriterion.cu:15`
So is there anybody who can help me to fix it? Thank you.

**Comment by Kongsea** [comment]
Please give me some advice @aadcock @vreis  Thank you.

**Comment by vreis** [comment]
@Kongsea: can you please share the code that you have right now?
