### ISSUE TITLE
the slack invite link is no longer active

### ISSUE THREAD

**Issue by acdart** [facebookresearch/ClassyVision#318]
This invite link is no longer active.
Please check with the person who shared it with you to see if there's a new link available.

**Comment by mannatsingh** [comment]
Thanks for pointing that out @acdart . @vreis can you figure out what's going on?

**Comment by vreis** [comment]
Fixed by https://github.com/facebookresearch/ClassyVision/pull/321 -- landing it now. Thanks for the report, @acdart!
