### ISSUE TITLE
No such file or directory: '/usr/local/lib/python3.6/dist-packages/classy_vision/templates/synthetic'

### ISSUE THREAD

**Issue by baidut** [facebookresearch/ClassyVision#331]
## 🐛 Bug

When installing it under a virtualenv, setting up a new project is not working because of FileNotFoundError

## To Reproduce

1. `mkvirtualenv myenv --python=python3.6; work on myenv`
1. `classy-project my_project`

## Environment

 - What commands did you use to install Classy Vision (conda/pip/build from source)? `pip install classy_vision`
 - What does `classy_vision.__version__` print? (If applicable)

```
>>> import classy_vision; print(classy_vision.__version__)
0.1.0
```

PyTorch version: 1.3.1
Is debug build: No
CUDA used to build PyTorch: 10.1.243

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: Could not collect

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: TITAN RTX
GPU 1: TITAN RTX

Nvidia driver version: 418.87.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.3
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7

Versions of relevant libraries:
[pip3] numpy==1.18.0
[pip3] torch==1.3.1
[pip3] torchvision==0.4.2
[conda] Could not collect

**Comment by baidut** [comment]
For those who want to install ClassyVision under a virtualenv

You will encounter two problems, I posted my solution here.

# module 'site' has no attribute 'getsitepackages'

Follow [this issue](https://github.com/NVIDIAGameWorks/kaolin/issues/6#issuecomment-557277725) to fix it

out of virtualenv, run

```
python3 -c 'import site; print(site.getsitepackages())'
gedit /home/zq/.virtualenvs/vqa/lib/python3.6/site.py
```
then add the following function to `site.py`
```
def getsitepackages():
    return ['/usr/local/lib/python3.6/dist-packages', '/usr/lib/python3/dist-packages', '/usr/lib/python3.6/dist-packages']
```

# No such file or directory: '/usr/local/lib/python3.6/dist-packages/classy_vision/templates/synthetic'

`sudo ln -s /home/your_user_name/.virtualenvs/venv/lib/python3.6/site-packages/classy_vision /usr/local/lib/python3.6/dist-packages`

**Comment by mannatsingh** [comment]
Thanks for reporting the issue and mentioning a fix, @baidut ! 

I was also able to repro the issue, this seems like a problem with virtualenv (https://github.com/pypa/virtualenv/issues/737) so I don't think there is anything to be fixed on our end. cc @vreis.
