### ISSUE TITLE
Conda install instructions in /README.md fail

### ISSUE THREAD

**Issue by fbbradheintz** [facebookresearch/ClassyVision#366]
## 📚 Documentation

The main README of the ClassyVision project on GitHub prescribes the following command line for installing the framework:

`conda install -c conda-forge classy_vision`

This gives the result:

```
--- ~ » conda install -c conda-forge classy_vision                                                                                                                     
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - classy_vision

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

Using `-c pytorch` and using no channel flag (i.e., `conda`'s default channels) produce similar results.

**Comment by vreis** [comment]
Thanks for the heads up! I can reproduce this. Looking into it now

**Comment by vreis** [comment]
In the meantime, please install classy vision from pip instead

**Comment by fbbradheintz** [comment]
That's what I did :)

**Comment by fbbradheintz** [comment]
Interestingly, anaconda.org search results show ClassyVision 0.2.0 on conda-forge: https://anaconda.org/search?q=classy_vision

**Comment by mannatsingh** [comment]
@fbbradheintz yes, that's true. `classy_vision` is only being built for linux currently. Let me try and see if I can get it to build for other environments.

**Comment by fbbradheintz** [comment]
Thanks for looking into it.

**Comment by mannatsingh** [comment]
`torchvision` is only available in the main channel for linux. conda-forge only allows picking up requirements from the main channel and the conda-forge channel. So there's no easy way to get the builds to work for other systems. I'm going to send a PR to update the README thought to only mention linux.
