### ISSUE TITLE
Is there a fancy way to implement NAS or Network Pruning?

### ISSUE THREAD

**Issue by kingsj0405** [facebookresearch/ClassyVision#384]
## ❓ Questions and Help

I wonder there is a fancy way to implement NAS(Neural Architecture Search) with classy-vision. 
I need to update not only weights of models but also architecture itself.
For example, [ProxylessNAS](https://github.com/mit-han-lab/ProxylessNAS).

**Comment by mannatsingh** [comment]
Hi @kingsj0405 , we don't have any specific code to support NAS. I think the best way right now to do NAS would be to write a new task.

**Comment by kingsj0405** [comment]
@mannatsingh Thank you. I'll try.
