### ISSUE TITLE
Where find  metadata_file in UCF101

### ISSUE THREAD

**Issue by fortunto2** [facebookresearch/ClassyVision#391]
## ❓ Questions and Help
Hi, i looking 
https://classyvision.ai/tutorials/video_classification

and i have my own dataset...
where i can find structure for metadata_file

```
metadata_file = "[PUT THE FILE PATH OF DATASET META DATA HERE]"

datasets = {}
datasets["train"] = build_dataset({
    "name": "ucf101",
    "split": "train",
    "batchsize_per_replica": 8,  # For training, we use 8 clips in a minibatch in each model replica
    "use_shuffle": True,         # We shuffle the clips in the training split
    "num_samples": 64,           # We train on 16 clips in one training epoch
    "clips_per_video": 1,        # For training, we randomly sample 1 clip from each video
    "frames_per_clip": 8,        # The video clip contains 8 frames
    "video_dir": video_dir,
    "splits_dir": splits_dir,
    "metadata_file": metadata_file,
    "fold": 1,
    "transforms": {
        "video": [
            {
                "name": "video_default_augment",
                "crop_size": 112,
                "size_range": [128, 160]
            }
        ]
    }
})
```

**Comment by vreis** [comment]
If you have your own dataset, please follow the instructions in https://classyvision.ai/tutorials/classy_dataset instead. That assumes you already have PyTorch code to generate a `torch.utils.data.Dataset`, and shows you how to integrate that with Classy Vision.

**Comment by vreis** [comment]
Answering the original question: here's the format for the metadata in `torchvision`: https://github.com/pytorch/vision/blob/master/torchvision/datasets/video_utils.py#L147

For each video, meta data contains the video file path, presentation timestamps of all video frames, and number of frames per second.

**Comment by vreis** [comment]
@fortunto2 : closing this out, feel free to reopen if you have any other questions

**Comment by RuyiLuo** [comment]
As for UCF101 dataset, how can I get the metadata file.
