### ISSUE TITLE
How to create resnext3d model?

### ISSUE THREAD

**Issue by XiaobingSuper** [facebookresearch/ClassyVision#396]
According to [API reference of ResNeXt3D](https://classyvision.ai/api/models.html), if I want to create a ResNeXt3D model, the parameter **num_groups** should be greater than 1, but for the test case in 
https://github.com/facebookresearch/ClassyVision/blob/6ed79d5e7ad40a55e409286326a7395192dd0f2a/test/models_resnext3d_test.py#L17-L29
the **num_groups** is 1, I'm confused it when I refer to https://github.com/facebookresearch/ClassyVision/blob/6ed79d5e7ad40a55e409286326a7395192dd0f2a/test/models_resnext3d_test.py#L50-L53.

I want to create a resnext3d model for video classification for UCF101 dataset, I find there have a config file in https://github.com/facebookresearch/ClassyVision/blob/master/classy_vision/configs/ucf101/r3d34.json, is it a resnet3d-34 model or resnext3d-34 model? Thanks!

**Comment by mannatsingh** [comment]
@XiaobingSuper ResNeXt models are just a generalization of ResNets, with the additional groups (or cardinality) parameter. If there is just one group for a ResNeXt model, it becomes a vanilla ResNet model  (`num_groups = 1`). 
Also, the config you're referring to has `num_groups == 1`, so it is a ResNet.
