### ISSUE TITLE
Make onnx exports compatible with TensorRT

### ISSUE THREAD

**Issue by crisp-snakey** [facebookresearch/ClassyVision#438]
## 🚀 Feature

The current use of either the reshape() or view() function in the [FullyConnectedHead](https://github.com/facebookresearch/ClassyVision/blob/dd468034322f4fe4fd05ff48dd022462235e83ae/classy_vision/heads/fully_connected_head.py#L74) of [FullyConvolutionalLinear](https://github.com/facebookresearch/ClassyVision/blob/dd468034322f4fe4fd05ff48dd022462235e83ae/classy_vision/heads/fully_convolutional_linear_head.py#L40) modules results in an onnx export that is not compatible with TensorRT.

## Motivation

TensorRT is the deep learning inference runtime from NVIDIA that allows for improved performance when running inference workloads on NVIDIA GPUs. The current implementation of the FullyConnectedHead and FullyConvolutionalLinear modules use either reshape or view in a manner that is incompatible with TensorRT and therefore when trying to import a model that has been exported to onnx will result in errors stating such.

The torchvision repository had the same problem as can be seen from [this issue](https://github.com/pytorch/vision/pull/1134)

## Pitch

Replace the use of both view() and reshape() with that of flatten().

**Comment by mannatsingh** [comment]
This makes sense. Thanks for sending a PR @crisp-snakey !
