### ISSUE TITLE
Examples for inference

### ISSUE THREAD

**Issue by SiftingSands** [facebookresearch/ClassyVision#460]
## ❓ Questions and Help

Documenting discussion from the ClassyVision slack channel about examples/best practices for inference.
Note : https://github.com/facebookresearch/ClassyVision/blob/master/tutorials/wsl_model_predict.ipynb shows an example for inference, but it is not referenced in the tutorials due to being unpolished.

Load model checkpoint
```
    task = build_task(config)

    # Load checkpoint, if available.
    if args.checkpoint_load_path is None:
        return print('NO CHECKPOINT PROVIDED')
    checkpoint = load_checkpoint(args.checkpoint_load_path)
    task.set_checkpoint(checkpoint)

    classy_interface = ClassyHubInterface.from_task(task)
```

Specify filepaths to images for inference 

```
    inference_root_dir =<HARD CODE OR IMPORT FROM YOUR CONFIG>
    inference_filepaths = []
    for image in os.listdir(inference_root_dir):
        inference_filepaths.append(os.path.join(inference_root_dir, image))
```

Specify image transforms and create dataloader
```
    Normalize = transforms.Normalize(mean = [0.485, 0.456, 0.406],
                                      std = [0.229, 0.224, 0.225])
    ToTensor = transforms.ToTensor()
    transforms_composed = transforms.Compose([ToTensor, Normalize])
    
    # Transform wrapper that says which key to apply the transform to
    transforms_composed_cv = ApplyTransformToKey(
        transform=transforms_composed,
        key="input",
    )
    
    dataset = classy_interface.create_image_dataset(image_paths = inference_filepaths, 
                                                    transform=transforms_composed_cv,
                                                    shuffle=False)
```

OR

Specify transforms from the config. @mannatsingh I couldn't get this to work.

Example portion from the config:
```
        "inference": {
            "name": "<REDACTED>",
            "filepaths": "<REDACTED>",
            "transforms": [{"name": "generic_image_transform", "transforms": [
                {"name": "ToTensor"},
                {
                    "name": "Normalize",
                    "mean": [0.485, 0.456, 0.406],
                    "std": [0.229, 0.224, 0.225]
                }
            ]}]
        }
```

Creating the dataset object
```
    dataset = classy_interface.create_image_dataset(
                                                    image_paths = config['dataset']['inference']['filepaths'],
                                                    shuffle=False,
                                                    phase_type = 'inference'
                                                    )
```
I believe this approach doesn't work for me, because my images for inference are not arranged in the following format. Naturally, the training/val set was setup in this manner, but obviously there are no classes for inference.

> 
>         root/dog/xxx.png
>         root/dog/xxy.png
>         root/dog/xxz.png
> 
>         root/cat/123.png
>         root/cat/nsdf3.png
>         root/cat/asd932_.png

Lastly, iterate through the dataset and compute class probabilities. (only doing batch size=1)

```
    classy_interface.eval()
    for input in dataset:
        input['input'] = input['input'].unsqueeze(0) # form the batch dimension
        output = classy_interface.predict(input)
        output = torch.nn.functional.softmax(output, dim=1) # this is obviously task dependent
```

**Comment by mannatsingh** [comment]
@SiftingSands sorry, I missed looking at this earlier.

Regarding your example with image paths, you're right, if you specify a single path, it is assumed to be structured as per `torchvision.datasets.ImageFolder`. You can always pass in all the paths to the images individually as a list, and that should work. This is obviously hard to do with a config, but maybe we can support a different directory structure as well, that should solve the issue for you.

Also, I noticed that you're passing the `phase_type` as `"inference"`. Instead, if you just specify the phase type as `"test"`, we will automatically pick the transform from the task (if you initialize the interface from the task), and you don't need to worry about specifying all the transforms again.

But this is very helpful in guiding us to understand what issues our users are facing, thanks for the write up!

**Comment by SiftingSands** [comment]
No worries at all.

Oh yeah, I forgot about about the 'phase_type' designation. I had added an "inference" key to the "dataset" dictionary in the config and wanted to see if it would pickup the transforms from there.

Regardless, my "boilerplate" setup is working well enough for my purposes. Closing this issue as I believe the documentation purposes of this ticket have been fulfilled.

**Comment by CaiyuZhang** [comment]
Hi, @SiftingSands  I also have question about inference, and I am confused about`classy_interface = ClassyHubInterface.from_task(task)` in your code, I cannot find source code about ClassyHubInterface or classy_interface in ClassyVision. Are those your own defined functions?  Please give me a hand, Thanks!

And @mannatsingh I have read your unpublished tutorial`wsl_model_predict.ipynb`. But it still don't give method to inference user's own images using trained model. So could I ask when will tutorial about 'inference' and 'transfer learning'  can be published, sorry to bother you, u can just reply me when u r available, Thanks!

**Comment by SiftingSands** [comment]
Try `from classy_vision.hub import ClassyHubInterface`

I believe there's already a tutorial for transfer learning/fine-tuning. https://classyvision.ai/tutorials/fine_tuning

However, I simply modified https://github.com/facebookresearch/ClassyVision/blob/master/classy_train.py to load in a custom dataset and pretrained model. There isn't a model zoo currently, so I just loaded model weights during model initialization instead of starting from a checkpoint.

**Comment by CaiyuZhang** [comment]
@SiftingSands Ok, thanks a lot for your work and reply :)

**Comment by CaiyuZhang** [comment]
@SiftingSands I of course have read the https://classyvision.ai/tutorials/fine_tuning, but this just teaches you to train a model and then change the number of class to fine-tune. But I mean I want to just download pretrained weights like pytorch and do transfer learning not training weights myself. You used https://github.com/facebookresearch/WSL-Images, and I will also have a try. Thanks for your reply again :)

**Comment by mannatsingh** [comment]
@SiftingSands thanks for helping out with the responses!

@CaiyuZhang I'm hoping to have a tutorial on using pre-trained external models and on inference before our next release, which should be happening in a couple of weeks.
