### ISSUE TITLE
Configuration argument explanation

### ISSUE THREAD

**Issue by CaiyuZhang** [facebookresearch/ClassyVision#476]
## ❓ Questions and Help
I am new to this repo, I haven't use configuration file to configure my task before, so I am confused about arguments in "lr" shown below such as "interval_scaling" etc, and I am thinking about the starting lr=0.1 maybe too big? Please help me out, thanks!  

this screenshot is made in "tutorial getting_started".
![image](https://user-images.githubusercontent.com/54944384/79038242-7274dd00-7c0a-11ea-9c95-b2de7b949188.png)

**Comment by mannatsingh** [comment]
Hi @CaiyuZhang ! The lr schedule the configuration at https://classyvision.ai/tutorials/getting_started#7.-Training-a-ResNet-50-on-ImageNet follows is based on the [Accurate, large minibatch sgd: Training imagenet in 1 hour](https://arxiv.org/abs/1706.02677) paper. Basically, the recommended lr schedule for ResNet 50 for an overall mini batch size of 256 (which is the case with 8 GPUs each with a batch size per replica of 32) is 0.1, with 1/10 drops at epochs 30, 60 and 80. For more a higher batch size, you linearly scale the lr, but you add a warm up for the first 5 epochs. I would highly recommend reading that paper, which should clarify these questions.

**Comment by CaiyuZhang** [comment]
@mannatsingh  Thanks for your reply and this amazing work!  I would read the paper later.  So the meaning of `"interval_scaling""lengths"`  is defined and expalined in this paper or that  just arguments defined in your code.

**Comment by CaiyuZhang** [comment]
@mannatsingh  I am thinking when training is done by using this "resnet" model that specified by my configuration file,  how do I use this trained model to inference ? I cannot find tutorials about inference.  Can I use this way shown below to perform inference?   
`with torch.no_grad():print(resnet(x))` , like this?

this image shows model part in my configuration file. 
![image](https://user-images.githubusercontent.com/54944384/79062216-9f88c480-7cca-11ea-9963-df7dac0530dd.png)

**Comment by mannatsingh** [comment]
@CaiyuZhang for the meanings of `"interval_scaling"` and `"lengths"` in the schedulers, check out the API docs for [`ParamScheduler`](https://classyvision.ai/api/param_scheduler.html), and [`CompositeParamScheduler`]( https://classyvision.ai/api/param_scheduler.html#classy_vision.optim.param_scheduler.CompositeParamScheduler). The latter also has an example explaining what everything means.

For inference, we need to publish our tutorial, but you could look at the examples @SiftingSands created in https://github.com/facebookresearch/ClassyVision/issues/460 to help out others :)

**Comment by CaiyuZhang** [comment]
@mannatsingh Ok, I would read later on, thanks to your patient reply :)
