### ISSUE TITLE
Add document how to use image path datasets

### ISSUE THREAD

**Issue by dsp6414** [facebookresearch/ClassyVision#504]
## 📚 Documentation
image path datasets tutorial

**Comment by dsp6414** [comment]
image_path-dataset.py

@classmethod
    def from_config(cls, config: Dict[str, Any]):
        """Instantiates ImagePathDataset from a config.

      ...
        return cls(
            batchsize_per_replica,
            shuffle,
            transform,
            num_samples,
-           image_folder=config.get("image_folder"),
-           image_files=config.get("image_files"),
+          image_folder=config.get("image_folder",None),
+          image_files=config.get("image_files",None),
        )

when there is no "image_files" item in config, it will execute error

**Comment by mannatsingh** [comment]
@dsp6414 I would recommend going over our [tutorial](https://classyvision.ai/tutorials/classy_dataset) about datasets and the docs for [`ImagePathDataset`](https://classyvision.ai/api/dataset.html#classy_vision.dataset.ImagePathDataset). If you face any issues, please let me know!

Regarding your second comment, `config.get("image_files") ` is equivalent to `config.get("image_files", None)`. So your modification should not make any difference. If you are getting any errors, could you report what exactly you ran and what the error was?
