### ISSUE TITLE
Will classyvision provide the function similar to Autogluon for automl in future.

### ISSUE THREAD

**Issue by dsp6414** [facebookresearch/ClassyVision#505]

**Comment by mannatsingh** [comment]
@dsp6414 I am not familiar with Autogluon, but looking at its [docs](https://autogluon.mxnet.io/), they mention that they cater to images, text and tabular data. Classy Vision is focused more specifically on image and video classification. 

If there are specific features you want to recommend from that toolkit, please list them down and also why you think they will be helpful :)
