### ISSUE TITLE
How to export ClassyModel 's state_dict to nn.Module 's state_dict?

### ISSUE THREAD

**Issue by dsp6414** [facebookresearch/ClassyVision#508]
## ❓ Questions and Help
 ClassyModel can use 'from_model' to load pytorch model, but how to export ClassyModel to pytorch model with weights

**Comment by mannatsingh** [comment]
This is covered in our [tutorial](https://classyvision.ai/tutorials/classy_model) for `ClassyModel`s. See the section on [Getting and setting the state of a model](https://classyvision.ai/tutorials/classy_model#Getting-and-setting-the-state-of-a-model).
