### ISSUE TITLE
Documentation on folder structure for video/image datasets

### ISSUE THREAD

**Issue by siddhantsahu** [facebookresearch/ClassyVision#527]
Please add more documentation on how you can create a new custom dataset to work with data loading utility functions.

It's much better to give an example on how these directories - `video_dir`, `splits_dir` are organized.

```
from classy_vision.dataset import build_dataset

# set it to the folder where video files are saved
video_dir = "[PUT YOUR VIDEO FOLDER HERE]"
# set it to the folder where dataset splitting files are saved
splits_dir = "[PUT THE FOLDER WHICH CONTAINS SPLITTING FILES HERE]"
# set it to the file path for saving the metadata
metadata_file = "[PUT THE FILE PATH OF DATASET META DATA HERE]"
```

**Comment by mannatsingh** [comment]
Sorry for not getting back to you sooner, @siddhantsahu !
For Image datasets, the [Getting Started](https://classyvision.ai/tutorials/getting_started) tutorial points to the documentation for how the directory structure should look like in the "Training a ResNet 50 on ImageNet" section.
The example in https://classyvision.ai/tutorials/video_classification uses the underlying [torchvision UCF-101 dataset](https://pytorch.org/docs/stable/torchvision/datasets.html#ucf101) so if you're familiar with that you should be good to go.
  
@stephenyan1231 can we try and add some documentation in the tutorial explaining `video_dir `, `splits_dir ` and `metadata_file `?

**Comment by lcskrishna** [comment]
@mannatsingh I do have same question regarding video_dir, split_dir and metadata_file. It would be great if you can provide more details of the UCF dataset structure from the above example you mentioned.

**Comment by mannatsingh** [comment]
@stephenyan1231 will add some information to this thread whenever he finds some time :)

**Comment by stephenyan1231** [comment]
Use UCF-101 dataset as an example.

Assume in your local folder, you have a `/data/ucf101` folder holding all videos.

- ucf101
   - ApplyEyeMakeup 
   ...
   - YoYo

You also have a folder `/data/UCF101TrainTestSplits-RecognitionTask` holding the splitting files of the dataset

- UCF101TrainTestSplits-RecognitionTask
   - classInd.txt
   ...
   - trainlist03.txt

You want to store meta data at `/data/ucf101_metadata.pt`.

Then you set 
  - video_dir = "/data/ucf101"
  - splits_dir = "/data/UCF101TrainTestSplits-RecognitionTask"
  - metadata_file = "/data/ucf101_metadata.pt"

Note, both videos and splitting files of UCF-101 dataset can be downloaded from the official site:  https://www.crcv.ucf.edu/data/UCF101.php
