### ISSUE TITLE
from classy_vision.tasks import ClassificationTask +ImportError: cannot import name 'broadcast'

### ISSUE THREAD

**Issue by kaushikCanada** [facebookresearch/ClassyVision#550]
Getting this error on importing the module.
from torch.distributed import broadcast
this is the line where it is occuring. any suggestions would be welcome.
THanks,

**Comment by mannatsingh** [comment]
Hi @kaushikCanada I'm sorry we missed looking at your issue earlier. It seems like you probably don't have PyTorch setup correctly. Can you make sure you by doing the following -

```
import torch
print(torch.__version__)  # should print something like 1.5
from torch.distributed import broadcast
```

If this doesn't work as expected, please try installing PyTorch as per https://pytorch.org/get-started/locally/

**Comment by kaushikCanada** [comment]
well i was trying it on windows and i think there might be issues. anywhere now i am trying it on ubuntu and it works. How is this different from pycls ?

**Comment by mannatsingh** [comment]
[pycls](https://github.com/facebookresearch/pycls) is "designed to support rapid implementation and evaluation of research ideas" whereas Classy Vision is meant to support research to production workflows within the same framework. Classy Vision is also associated with documentation for all its [API](https://classyvision.ai/api/) and some [tutorials](https://classyvision.ai/tutorials/) to help you get started and decide if it can cater to your use-case!
