### ISSUE TITLE
QuantNoise implementation for ClassyVision models

### ISSUE THREAD

**Issue by jmatak** [facebookresearch/ClassyVision#558]
## 🚀 Feature
I know Product Quantization models trained using [QuantNoise](https://ai.facebook.com/blog/training-with-quantization-noise-for-extreme-model-compression/) were tested, but never fully open-sourced in ClassyVision. When will, Quantization Noise API be available, and when will pre-trained models be open-sourced.

**Comment by mannatsingh** [comment]
@jmatak some of the pieces required to train the baseline models have not been open sourced in Classy yet. We can try and work on moving these out and also chat with the authors to see if we can release the models once that is done in a month or two.
cc @pierrestock

**Comment by thimabru1010** [comment]
Yes, I didn't find them too. So they aren't available yet? Do you have any idea when you will release training with [Extreme Quant Noise](https://ai.facebook.com/blog/training-with-quantization-noise-for-extreme-model-compression/) from paper

**Comment by mannatsingh** [comment]
Hi guys, I have discussed this with @pierrestock , we will try and release the implementation in this quarter.

**Comment by jmatak** [comment]
@mannatsingh Please inform me once when implementation is available for public usage.

**Comment by mannatsingh** [comment]
Hi @MohammedHAlali we were never able to get around to it sadly and have no plans on supporting QuantNoise in Classy Vision anymore unfortunately. Sorry!
