### ISSUE TITLE
Synchronized Batch Normalization is disabled

### ISSUE THREAD

**Issue by shinianzhihou** [facebookresearch/ClassyVision#681]
How to open Synchronized BN during the training process?

thx!!!

**Comment by mannatsingh** [comment]
If you're running with a config, you can pass the following key in the task configuration - 

```python
{
    ...
    "distributed": {"batch_norm_sync_mode": <sync_mode>} # <sync_mode> can be "pytorch" or "apex"
}
```

If using the "apex" mode, you can also enable syncing over a smaller group size. For intra node sync batch norm, the setting should like -

```python
{
    ...
    "distributed": {"batch_norm_sync_mode": "apex", "batch_norm_sync_group_size": 8}
}
```

Hope this helps!

**Comment by shinianzhihou** [comment]
It helps a lot! thx!
