### ISSUE TITLE
Unclear what trunc_normal init is. 

### ISSUE THREAD

**Issue by karttikeya** [facebookresearch/ClassyVision#683]
## 🐛 Bug

Vision Transformer uses `torch.nn.init.trunc_normal_` ([here](https://github.com/facebookresearch/ClassyVision/blob/436b79a82c1b3f7ccdc138a2a3f95c2f95488657/classy_vision/models/lecun_normal_init.py)) which is not yet available in `torch.nn.init`  (in pytorch 1.4). Is this expected behavior?

**Comment by mannatsingh** [comment]
Ah yeah, you're right @karttikeya - this only would work with pytorch 1.7. To unblock yourself, you can upgrade to that. In the meantime, I will send a PR to fix this for older pytorch versions

**Comment by mannatsingh** [comment]
Fixed in https://github.com/facebookresearch/ClassyVision/pull/690
