### ISSUE TITLE
update breaking changes of v0.5 release in README.md

### ISSUE THREAD

**Issue by AjinkyaIndulkar** [facebookresearch/ClassyVision#684]
## 📚 Documentation

https://github.com/facebookresearch/ClassyVision#breaking-changes section of README.md needs to be updated: 

Renamed `is_master` to `is_leader` in `distributed_util` (#576) -> Renamed `is_master` to `is_primary` in `distributed_util` (#576)

**Comment by mannatsingh** [comment]
Thanks so much for catching that @AjinkyaIndulkar , let me fix it!
