### ISSUE TITLE
How to visualize the feature map in tensorboard?

### ISSUE THREAD

**Issue by shinianzhihou** [facebookresearch/ClassyVision#710]
## ❓ Questions and Help

How to visualize the feature map in tensorboard?

I try to sign in to the provided slack but failed.

Could you pls provide some advice about how to visualize the feature map on tensorboard ? Using tensorboard hook?

**Comment by mannatsingh** [comment]
@shinianzhihou sorry for the delay in responding. I would recommend writing a hook similar to the default [`TensorboardHook`](https://github.com/facebookresearch/ClassyVision/blob/master/classy_vision/hooks/model_tensorboard_hook.py) for this. We visualize the parameters which can help serve as a reference.
