### ISSUE TITLE
Getting started Tutorial doesn't work

### ISSUE THREAD

**Issue by jsuit** [facebookresearch/ClassyVision#731]
So I'm trying to follow the getting_started tutorial. 
I `cd` into the folder that was just created by classy-project and run
```./classy_train.py --config configs/template_config.json```

I get the error message: 

```sage: classy_train.py [--help] [--hydra-help] [--version]
                       [--cfg {job,hydra,all}] [--package PACKAGE] [--run]
                       [--multirun] [--shell-completion]
                       [--config-path CONFIG_PATH] [--config-name CONFIG_NAME]
                       [--config-dir CONFIG_DIR] [--info]
                       [overrides [overrides ...]]
classy_train.py: error: ambiguous option: --config could match --config-path, --config-name, --config-dir
```

**Comment by mannatsingh** [comment]
Hi @jsuit ! It looks like you have [hydra](https://hydra.cc/docs/intro) installed in your setup. Classy has experimental and undocumented hydra support - for the tutorial to work correctly, you will need to uninstall hydra.

**Comment by mannatsingh** [comment]
Closing this issue. Please feel free to reopen if removing hydra doesn't solve your issue.
