### ISSUE TITLE
how to print 'sub loss' 

### ISSUE THREAD

**Issue by fangwudi** [facebookresearch/ClassyVision#751]
How can I log values of each sub loss in SumArbitraryLoss or MultiOutputSumLoss  just like the way in keras .
For exsample: tain log, total loss:  x, sub loss 1: x1, sub loss 2: x2 .

**Comment by mannatsingh** [comment]
This isn't directly supported. But you should be able to create a hook that derives from `LossLrMeterLoggingHook` and override this section - https://github.com/facebookresearch/ClassyVision/blob/master/classy_vision/hooks/loss_lr_meter_logging_hook.py#L72-L77

**Comment by fangwudi** [comment]
> https://github.com/facebookresearch/ClassyVision/blob/master/classy_vision/hooks/loss_lr_meter_logging_hook.py#L72-L77

Ok, thanks.
