### ISSUE TITLE
train using num_steps

### ISSUE THREAD

**Issue by fangwudi** [facebookresearch/ClassyVision#752]
## ❓ Questions and Help

how to train using num_steps instead of num_epochs?

**Comment by mannatsingh** [comment]
Hi @fangwudi we don't directly support specifying num_steps, but you can tune the number of steps by changing `num_epochs` (and optionally `num_samples` in the dataset).

**Comment by fangwudi** [comment]
> Hi @fangwudi we don't directly support specifying `num_steps`, but you can tune the number of steps by changing `num_epochs` (and optionally `num_samples` in the dataset).

thanks, I'm using this method
