### ISSUE TITLE
Get Dataset's Prediction

### ISSUE THREAD

**Issue by fangwudi** [facebookresearch/ClassyVision#756]
## ❓ Questions and Help

Is there any easy way to get total prediction of one dataset's testset? Do not need meters, only prediction is needed.

**Comment by mannatsingh** [comment]
Do you mean getting all the predictions for a dataset? You can use https://github.com/facebookresearch/ClassyVision/blob/master/classy_vision/hooks/output_csv_hook.py for that. If you just want to run inference, you can call `set_test_only` to `True`.

**Comment by fangwudi** [comment]
> Do you mean getting all the predictions for a dataset? You can use https://github.com/facebookresearch/ClassyVision/blob/master/classy_vision/hooks/output_csv_hook.py for that. If you just want to run inference, you can call `set_test_only` to `True`.
> 
> If you just want aggregate counts, then you can simply write a custom meter which reports this :)

thanks. I think output_csv_hook maybe helpful.
