### ISSUE TITLE
process hangs and no logs showing.

### ISSUE THREAD

**Issue by jpainam** [facebookresearch/ClassyVision#763]
## 🐛 Bug
I'm facing too many difficulties with this library. Going to move back to normal PyTorch.
This is the code for training after following the Video classification code.
```python
import time
import os

from classy_vision.trainer import LocalTrainer
from classy_vision.hooks import CheckpointHook
from classy_vision.hooks import LossLrMeterLoggingHook

hooks = [LossLrMeterLoggingHook(log_freq=1)]

checkpoint_dir = f"./checkpoints/checkpoint_{time.time()}"
os.mkdir(checkpoint_dir)
hooks.append(CheckpointHook(checkpoint_dir, input_args={}))
task = task.set_hooks(hooks)
trainer = LocalTrainer()
trainer.train(task)
```
This error `ValueError: Cannot register duplicate param scheduler (step)`, keeps on coming randomly. Even after Kernel restarted in Jupyter.

**Comment by mannatsingh** [comment]
I am looking into the param scheduler issue in https://github.com/facebookresearch/ClassyVision/issues/762. For the hanging, it's probably just that the logging hasn't been set up. For posterity, the code is probably not hanging - it's just not logging anything. That can be fixed by running -

```python
import logging

logger = logging.getLogger()
logger.setLevel(logging.INFO)

```
